# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ 3.9 ]
  pull_request:
    branches: [ 3.9 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      working-directory: releng/org.eclipse.rap.e4.compatibility.workbench.build
      run: mvn install
      
    # Copy files
    # Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
    - task: CopyFiles@2
       inputs:
       sourceFolder: releng/org.eclipse.rap.e4.compatibility.workbench.build/repository/target # Optional
       #contents: '**' 
       targetFolder: /
    #cleanTargetFolder: false # Optional
    #overWrite: false # Optional
    #flattenFolders: false # Optional
    #preserveTimestamp: false # Optional
